from langchain.tools import tool

@tool
def format_marketing_plan(plan_content: str) -> str:
    """
    Use this to output the final formatted marketing or content plan.
    Pass the complete plan text as the argument.
    Call this as the LAST step, after you have gathered all data and insights.
    """
    return f"""
## Marketing Plan

{plan_content}

---
*Generated by Marketing AI Agent based on your company data and current market research.*
"""